***
## 자연어 처리

-문장을 바로 처리하기 힘들기 때문에 단어로 처리

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
doce = ['There is a boy.',
 'The boy is ver pretty.',
  'The vernacular was not the stuff of parliamentary propriety — “I need to take a minute,” he wrote about stepping back from the trail — but that was the point, as is often the case with Fetterman. At 6-foot-8, with a shiny pate, a salt-and-pepper goatee, tattooed arms and a sports-bar fashion sense, Fetterman was announcing from a hospital bed that even in illness he remained a different kind of Democrat.',
  'Republicans were set to choose Tuesday among three leading Senate candidates in a hard-fought primary contest — physician and celebrity Mehmet Oz, backed by Trump; financier David McCormick; and upstart Kathy Barnette, who on Jan. 6, 2021, participated in the “Stop the Steal” rally that preceded the violent assault on the U.S. Capitol.']

In [3]:
data = []
for s in doce:
    s2= s.replace('.', '')
    s2 = s2.lower()
    data.append(s2.split())
    
data

[['there', 'is', 'a', 'boy'],
 ['the', 'boy', 'is', 'ver', 'pretty'],
 ['the',
  'vernacular',
  'was',
  'not',
  'the',
  'stuff',
  'of',
  'parliamentary',
  'propriety',
  '—',
  '“i',
  'need',
  'to',
  'take',
  'a',
  'minute,”',
  'he',
  'wrote',
  'about',
  'stepping',
  'back',
  'from',
  'the',
  'trail',
  '—',
  'but',
  'that',
  'was',
  'the',
  'point,',
  'as',
  'is',
  'often',
  'the',
  'case',
  'with',
  'fetterman',
  'at',
  '6-foot-8,',
  'with',
  'a',
  'shiny',
  'pate,',
  'a',
  'salt-and-pepper',
  'goatee,',
  'tattooed',
  'arms',
  'and',
  'a',
  'sports-bar',
  'fashion',
  'sense,',
  'fetterman',
  'was',
  'announcing',
  'from',
  'a',
  'hospital',
  'bed',
  'that',
  'even',
  'in',
  'illness',
  'he',
  'remained',
  'a',
  'different',
  'kind',
  'of',
  'democrat'],
 ['republicans',
  'were',
  'set',
  'to',
  'choose',
  'tuesday',
  'among',
  'three',
  'leading',
  'senate',
  'candidates',
  'in',
  'a',
  'hard-fought',
  'p

## 딕셔너리(dictionary)
- ``사람은 누구든지 "이름" = "홍길동", "생일" = "몇 월 며칠" 등으로 구별할 수 있다. 파이썬은 영리하게도 이러한 대응 관계를 나타낼 수 있는 자료형을 가지고 있다. 요즘 사용하는 대부분의 언어도 이러한 대응 관계를 나타내는 자료형을 갖고 있는데, 이를 연관 배열(Associative array) 또는 해시(Hash)라고 한다.``

- ``ex) dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}``

|dic|key|value|
|---|---|-----|
|---|name|pey|
|---|phone|01199993323|
|---|birth|1118|



In [4]:
bow = {}
n = 0

for doc in data:
    for word in doc:
        if word not in bow:
            bow[word] = n
            n += 1
            
            
bow

{'there': 0,
 'is': 1,
 'a': 2,
 'boy': 3,
 'the': 4,
 'ver': 5,
 'pretty': 6,
 'vernacular': 7,
 'was': 8,
 'not': 9,
 'stuff': 10,
 'of': 11,
 'parliamentary': 12,
 'propriety': 13,
 '—': 14,
 '“i': 15,
 'need': 16,
 'to': 17,
 'take': 18,
 'minute,”': 19,
 'he': 20,
 'wrote': 21,
 'about': 22,
 'stepping': 23,
 'back': 24,
 'from': 25,
 'trail': 26,
 'but': 27,
 'that': 28,
 'point,': 29,
 'as': 30,
 'often': 31,
 'case': 32,
 'with': 33,
 'fetterman': 34,
 'at': 35,
 '6-foot-8,': 36,
 'shiny': 37,
 'pate,': 38,
 'salt-and-pepper': 39,
 'goatee,': 40,
 'tattooed': 41,
 'arms': 42,
 'and': 43,
 'sports-bar': 44,
 'fashion': 45,
 'sense,': 46,
 'announcing': 47,
 'hospital': 48,
 'bed': 49,
 'even': 50,
 'in': 51,
 'illness': 52,
 'remained': 53,
 'different': 54,
 'kind': 55,
 'democrat': 56,
 'republicans': 57,
 'were': 58,
 'set': 59,
 'choose': 60,
 'tuesday': 61,
 'among': 62,
 'three': 63,
 'leading': 64,
 'senate': 65,
 'candidates': 66,
 'hard-fought': 67,
 'primary': 68,
 'co

In [5]:
bow2 = {}

for k, v in bow.items():
    bow2[v] = k

bow2

{0: 'there',
 1: 'is',
 2: 'a',
 3: 'boy',
 4: 'the',
 5: 'ver',
 6: 'pretty',
 7: 'vernacular',
 8: 'was',
 9: 'not',
 10: 'stuff',
 11: 'of',
 12: 'parliamentary',
 13: 'propriety',
 14: '—',
 15: '“i',
 16: 'need',
 17: 'to',
 18: 'take',
 19: 'minute,”',
 20: 'he',
 21: 'wrote',
 22: 'about',
 23: 'stepping',
 24: 'back',
 25: 'from',
 26: 'trail',
 27: 'but',
 28: 'that',
 29: 'point,',
 30: 'as',
 31: 'often',
 32: 'case',
 33: 'with',
 34: 'fetterman',
 35: 'at',
 36: '6-foot-8,',
 37: 'shiny',
 38: 'pate,',
 39: 'salt-and-pepper',
 40: 'goatee,',
 41: 'tattooed',
 42: 'arms',
 43: 'and',
 44: 'sports-bar',
 45: 'fashion',
 46: 'sense,',
 47: 'announcing',
 48: 'hospital',
 49: 'bed',
 50: 'even',
 51: 'in',
 52: 'illness',
 53: 'remained',
 54: 'different',
 55: 'kind',
 56: 'democrat',
 57: 'republicans',
 58: 'were',
 59: 'set',
 60: 'choose',
 61: 'tuesday',
 62: 'among',
 63: 'three',
 64: 'leading',
 65: 'senate',
 66: 'candidates',
 67: 'hard-fought',
 68: 'primary',
 69:

In [6]:
X = []

for doc in data:
    l = []
    for word in doc:
        l.append(bow[word])
    X.append(l)
X

[[0, 1, 2, 3],
 [4, 3, 1, 5, 6],
 [4,
  7,
  8,
  9,
  4,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  2,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  4,
  26,
  14,
  27,
  28,
  8,
  4,
  29,
  30,
  1,
  31,
  4,
  32,
  33,
  34,
  35,
  36,
  33,
  2,
  37,
  38,
  2,
  39,
  40,
  41,
  42,
  43,
  2,
  44,
  45,
  46,
  34,
  8,
  47,
  25,
  2,
  48,
  49,
  28,
  50,
  51,
  52,
  20,
  53,
  2,
  54,
  55,
  11,
  56],
 [57,
  58,
  59,
  17,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  51,
  2,
  67,
  68,
  69,
  14,
  70,
  43,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  43,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  51,
  4,
  89,
  4,
  90,
  91,
  28,
  92,
  4,
  93,
  94,
  84,
  4,
  95,
  96]]

## 원-핫 인코딩 (one-hot Encoding)
자연어를 컴퓨터가 처리하도록 문자를 기계가 이해할수있는 숫자형태로 바꾸는 그과정을 임베딩(Embedding) 이라고합니다


- 원-핫 인코딩은 단어 집합의 크기를 벡터의 차원으로 하고, 표현하고 싶은 단어의 인덱스에 1의 값을 부여하고, 다른 인덱스에는 0을 부여하는 벡터 표현 방식입니다.

- 한자리만 맞는걸 원-핫 인코딩이라고 말한다.


ex)
|단어|단어인덱스|원-핫 벡터|
|----|----------|----------|
|you|0|[1,0,0,0,0,0]|
|say|1|[0,1,0,0,0,0]|
|goodbye|2|[0,0,1,0,0,0]|
|and|3|[0,0,0,1,0,0]|

In [7]:
# 원핫인코딩

X2 = []

for x in X:
    a = np.eye(n + 1)[x]
    X2.append(a)

X2

[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.

In [8]:
np.eye(n + 1)[10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

***
## 직접 데이터 가져와서 해보기
#### https://github.com/rickiepark/introduction_to_ml_with_python/blob/master/data/aclImdb_v1.tar.gz
***

In [9]:
from sklearn.datasets import load_files

imdb_train = load_files('data/aclImdb/train/')
imdb_test = load_files('data/aclImdb/test/')

np.save('imdb.npy', [imdb_train, imdb_test])

In [10]:
type(imdb_train), type(imdb_test)

(sklearn.utils.Bunch, sklearn.utils.Bunch)

In [11]:
imdb_train.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [12]:
type(imdb_train.data), len(imdb_train.data)

(list, 25000)

In [13]:
type(imdb_test.data), len(imdb_test.data)

(list, 25000)

In [14]:
imdb_train.data[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [15]:
imdb_train.data[0].decode()

"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

In [16]:
# <br> 제거

text_train = [s.decode().replace('<br />', '') for s in imdb_train.data]
len(text_train)

25000

In [17]:
y_train = imdb_train.target
display(y_train.shape, y_train)

(25000,)

array([1, 0, 1, ..., 0, 0, 0])

In [18]:
# 뭘 더해야 12500 나오는거지?,,
# -> 아,, y_train 하면 1,0.....0,0,0 이렇게 나오니깐 1만 더하면 12500나오는거네

sum(y_train)

12500

In [19]:
text_test = [s.decode().replace('<br />', '') for s in imdb_test.data] 
len(text_test)

25000

In [38]:
y_test = imdb_test.target
display(y_test.shape, y_test)

(25000,)

array([1, 0, 1, ..., 0, 0, 0])

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
vect = CountVectorizer()
vect.fit(text_train)
X_train = vect.transform(text_train)

In [23]:
X_train

<25000x75911 sparse matrix of type '<class 'numpy.int64'>'
	with 3431163 stored elements in Compressed Sparse Row format>

In [24]:
type(vect.vocabulary_), len(vect.vocabulary_)

(dict, 75911)

In [25]:
for i, (k, v) in enumerate(vect.vocabulary_.items()):
    print(k, v)
    if i == 10: break

zero 75669
day 16986
leads 38653
you 75381
to 68091
think 67468
even 23059
re 54503
why 73998
two 69757
boys 8922


In [26]:
for i, (k, v) in enumerate(vect.vocabulary_.items()):
    print(k, v)
    if k == 'love': break

zero 75669
day 16986
leads 38653
you 75381
to 68091
think 67468
even 23059
re 54503
why 73998
two 69757
boys 8922
young 75392
men 42764
would 74762
do 19634
what 73731
they 67409
did 18588
commit 13888
mutual 45268
suicide 65104
via 72211
slaughtering 61588
their 67280
classmates 12958
it 35211
captures 10809
must 45209
be 6512
beyond 7341
bizarre 7716
mode 43993
of 47352
being 6852
for 25839
humans 32540
who 73935
have 30570
decided 17219
withdraw 74379
from 26582
common 13907
civility 12845
in 33505
order 47900
define 17460
own 48610
world 74699
coupled 15414
destruction 18214
is 35099
not 46714
perfect 49947
movie 44779
but 10096
given 28034
money 44193
time 67883
the 67244
filmmaker 24942
and 3375
actors 1741
had 29807
remarkable 55513
product 52605
terms 67035
explaining 23541
motives 44676
actions 1723
murderers 45110
better 7288
than 67198
elephant 21607
film 24904
that 67222
gets 27726
under 70279
our 48156
rationalistic 54367
skin 61440
far 24147
almost 2880
anything 3859
are 

In [27]:
vect.vocabulary_['love']

40154

In [28]:
feature_names = vect.get_feature_names()
display(type(feature_names), len(feature_names))
display(feature_names[:5], feature_names[20010:20015], feature_names[::10000])

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


list

75911

['00', '000', '0000000000001', '00001', '00015']

['doppelgangers', 'doppelgänger', 'dopplebangers', 'doppleganger', 'doppler']

['00',
 'burress',
 'dop',
 'hallucinogenics',
 'looping',
 'periphery',
 'shaffer',
 'una']

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [30]:
X_test = vect.transform(text_test)
X_test.shape

(25000, 75911)

In [31]:
model = LogisticRegression(C=0.1, max_iter=500)
model.fit(X_train, y_train)

LogisticRegression(C=0.1, max_iter=500)

In [37]:
score = model.score(X_test, y_test)
score

0.87884

In [ ]:
model.score(X_train, y_train)

0.97504

In [39]:
w = model.coef_[0] # 기울기 값
type(w), w.shape # 값이 크면... 값도 75911 단어수고 75911,, 기울기 값이 크면 긍정효과를 나타낸다... 왜? 기울기 값이 작으면 부정적 아래 뽑아보자

(numpy.ndarray, (75911,))

In [40]:
fn = np.array(vect.get_feature_names())

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [41]:
indexer = w.argsort()

fn[indexer[:20]] # 큰 음수값들, 즉 부정적인 영향을 끼침

array(['worst', 'waste', 'awful', 'disappointment', 'poorly', 'boring',
       'lacks', 'disappointing', 'mess', 'horrible', 'avoid', 'worse',
       'fails', 'dull', 'save', 'poor', 'laughable', 'unfortunately',
       'terrible', 'lame'], dtype='<U74')

In [43]:
fn[indexer[-1:-21:-1]] # 큰 양수값들, 즉 긍정적인영향을 끼침

array(['excellent', 'perfect', 'refreshing', 'superb', 'wonderfully',
       'funniest', 'surprisingly', 'wonderful', 'rare', 'favorite',
       'enjoyable', 'amazing', 'loved', 'today', 'highly', 'incredible',
       'enjoyed', 'subtle', 'brilliant', 'gem'], dtype='<U74')